name: Deploy to Google Cloud Storage

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Static Web to GCS
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    env:
      BUCKET_NAME: gcr-website-bucket
      TURSO_DATABASE_URL: ${{ secrets.TURSO_DATABASE_URL }}
      TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Seed db with Turso
        run: npm run seed

      - name: Build Astro
        run: pnpm run build
      
      - name: Clear bucket before upload
        run: gsutil -m rm -r gs://${{ env.BUCKET_NAME }}/client/**

      - name: Upload to GCS
        run: gsutil -m rsync -r -d -c dist/client/ gs://${{ env.BUCKET_NAME }}/client/

      - name: Fix JS MIME types
        run: |
          gsutil -m setmeta -h "Content-Type:application/javascript" \
            $(gsutil ls gs://${{ env.BUCKET_NAME }}/client/_astro/*.js || true)
