name: Deploy to Google Cloud Storage

on:
  push:
    branches:
      - main
  workflow_dispatch:  

jobs:
  deploy:
    name: Deploy Static Web to GCS
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'  
      
    env:
      BUCKET_NAME: gcr-website-bucket 
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'
          
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '22' 
      
      - name: Install pnpm
        run: npm install -g pnpm
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Push to db Astro
        run: pnpm astro db push --remote false

      - name : Seed db Astro
        run: pnpm astro db seed

      - name: Build Astro
        run: pnpm run build
      
      - name: Upload to GCS
        run: |
          gsutil -m cp -r dist/* gs://${{ env.BUCKET_NAME }}/

      - name: Deploy to GCS
        run: |
          gsutil -m cp -r . gs://${{ env.BUCKET_NAME }}/
